name: CD Front-end (netlify)

on:
  workflow_dispatch:

jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Netlify
    steps:
      - name: restaurar cache
        uses: actions/cache@v3
        with:
          path: front-end/dist/
          key: build-${{github.sha}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cópia do arquivo netlify.toml
        run: cp front-end/netlify.toml front-end/dist/sgcmapp/
      - name: Instalação do clente Netlify
        run: npm install -g netlify/cli
      - name: deploy
        run: netlify deploy --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=front-end/dist/sgcmapp --site=${{ secrets.NETLIFY-SITE-ID }} --prod
